services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./demo_pageviews.csv:/docker-entrypoint-initdb.d/demo_pageviews.csv

  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana-oss
    container_name: portfolio_grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pgdata:
  grafana_data:
